### ISSUE TITLE
Doesn't seem to be working in ST3 3144

### ISSUE THREAD

**Issue by Asuza** [soandrew/DiffTabs#3]
I can't figure out what's wrong with DiffTabs. I installed it via package control, but there's no errors in console, none of the context menus are present, and none of the commands are available from the command palette.

Is there anything I can do to debug this problem? Nothing else compares to DiffTabs, so I'd love to get it working again.

Thanks!

**Comment by soandrew** [comment]
Hi, unfortunately I don't have access to build 3144 since it's still a dev build. I've tested on build 3143 and it seems to work fine and from the change log I don't see any obvious reason why it would stop working with 3144.

Here are some steps you can take to troubleshoot:
1. Open Sublime
2. Open the console (View -> Show console)
3. Check if there is a line of text that says something to the effect of  "reloading plugin DiffTabs"
If you don't have any line like this, double check your Packages directory to ensure DiffTabs has been installed.
4. Open a new file (File ->New File)
5. Open a new file again
6. In the tab bar along the top, right click the other tab (not the currently open tab)
In the context menu there should be the option to "Diff with current tab..."

Give those a try and let me know if you reached step 6 and don't see the context menu option.

**Comment by Asuza** [comment]
The console shows the message (no errors anywhere):
```
reloading plugin DiffTabs.diff_tabs
```
I opened a couple of new files and tried to access the context menu via the tab, but it's not there.

**Comment by soandrew** [comment]
Thanks for the info. If the plugin is being loaded and still no context menu is showing, then it appears that some aspect of the Sublime API has changed with the new build. Unfortunately, until it gets released as a public build, I can't investigate any further and (hopefully) release a fix.

For now, if you really need the plugin then I'd recommend switching back to the 3143 build. I'm assuming that it worked before?

**Comment by Asuza** [comment]
I'm not entirely certain if it worked before, as this is the first time I've installed it on this computer. I'll try to report back tomorrow on whether 3143 works fine (though that will be a different computer...).

**Comment by Asuza** [comment]
Well, it's working fine on 3142. It seems that's the version I have installed. I've had it installed there for a long time, though. No idea if that matters.

**Comment by soandrew** [comment]
Glad to hear that! I'll try to release a fix for newer builds once they become available.

**Comment by Asuza** [comment]
Okay, just to be certain, I updated my ST 3142 to 3144 and your plug-in is still working fine. There must be some plugin I have installed on my home machine that's conflicting with yours. I don't know what else it would be at this point.

**Comment by soandrew** [comment]
Well then. I'm relieved to hear that the problem (probably) isn't with my code. It's strange though since plugins should be relatively isolated from each other. Only thing I can recommend is to start from a fresh install of Sublime and then add plugins one at a time to see where the conflict could be.
