### ISSUE TITLE
No context menu with build 3170

### ISSUE THREAD

**Issue by tamastimar** [soandrew/DiffTabs#4]
I've just installed ST 3.1 3170 (called 3.0 3170 in About dialog) and the package stopped working, no Diff... entry in context menu.

**Comment by soandrew** [comment]
Hi, Sublime doesn't provide downloads for older builds so I used the latest available build (3176) in order to try and recreate the issue, but I haven't been able to replicate it. The package appears to be working fine in this latest build. If possible, could you update Sublime and see if the issue still occurs?

**Comment by tamastimar** [comment]
Indeed, it works with the latest build.
Thanks.

**Comment by geoidesic** [comment]
seems to be broken again v3.2.2 Build 3211

**Comment by soandrew** [comment]
@geoidesic Hey, sorry for the delayed response. I am on a brand new install of version 3.2.2, build 3211 with the package installed myself and everything seems to work as expected on my end. If you are still encountering problems, could I bother you to open a new issue (green button in the top right of this page) so that I can track your issue better.

**Comment by geoidesic** [comment]
Maybe I just don't know where to click to get the menu? 
I tried right-clicking in the file body but I just get the standard context menu.
I tried right-clicking on the tab handle itself but I also just get the standard context menu.

If I'm not just doing it wrong, let me know and then I'll open a new ticket (although I'm not sure what to put in the ticket that's not already in here, is it not worth just re-opening this ticket?)

**Comment by soandrew** [comment]
@geoidesic Ah no worries, can you try the following steps:

1. Open Sublime
2. Open a new file (File ->New File)
3. Open a new file again
4. In the tab bar along the top, right click the other tab (not the currently open tab). In the context menu there should be the option to "Diff with current tab..."

Give that a try and let me know how it goes. I general you just need two files open and to right click on the tab you are not currently on.

**Comment by geoidesic** [comment]
Right... I've been doing it wrong. I was expecting it to work the other way around. I.e. right-click on the current tab which then shows option to "Diff with last viewed tab".

**Comment by soandrew** [comment]
@geoidesic Glad to hear that it works for you. The design is helpful for situations where users may have multiple tabs open so they can directly choose which of the multiple other tabs they want to compare the current tab with. Instead of having to remember which tab they viewed last.
