### ISSUE TITLE
Included in Sublime Text build 4140

### ISSUE THREAD

**Issue by themilkman** [soandrew/DiffTabs#8]
Hi there,

first of all thanks for your plugin! It was very useful for me. 
I just wanted to point out that as of ST build 4140 the functionality should be shipped with ST itself, see: https://github.com/sublimehq/Packages/pull/3315 is merged and fixes https://github.com/sublimehq/Packages/issues/3313.

Nevertheless it is still useful for older builds.

Cheers and thanks again for your work!

**Comment by BarbzYHOOL** [comment]
i just installed it, it's the only good diff plugin, all the others are convoluted and bloated

and now i realize i can uninstall it and update ST xD

**Comment by themilkman** [comment]
Yes, the plugin really does, what it says and nothing else - always liked that, too.
Currently not sure whether it is possible out of the box to open the diff in a tab instead of the panel.

**Comment by BarbzYHOOL** [comment]
you prefer in a tab or inside the panel? i never use the panel but i felt like it's okay (only tried once)

**Comment by soandrew** [comment]
@themilkman hey, thanks for letting me know about this being a built-in feature now in ST4. Tested it out and the update is definitely going to be confusing for existing plugin users because there's now two options with the exact same name...
![image](https://user-images.githubusercontent.com/15936962/201425408-72056efc-e232-4061-9102-18a5e1543a47.png)

The diff behaviour is also slightly different as I think y'all have mentioned above
- Results open in a panel instead of a tab
- The tabs considered to be "from" and "to" are also switched
![image](https://user-images.githubusercontent.com/15936962/201425755-3f9985dd-57f7-42cc-aff2-0f7fcd29e940.png)

I'm probably biased but I personally like my plugin's "from" and "to" behaviour more, it's more intuitive I feel. As for displaying results in panel vs tab, I preferred tab because I could freely move the tab to wherever I want and also I could save the results as a patch file if desired.

I'm not too sure what the best path moving forward is though:
1. I could delist this plugin for ST4? Keep this as just a ST2/3 plugin?
2. I could change the context menu option name just for ST4 to distinguish the plugin from the built-in?
3. Is there a request to make the "from/to" and the "panel vs tab" behaviour customizable as a plugin option?

**Comment by BarbzYHOOL** [comment]
i think you're right, your plugin seems better, damnit, maybe ask (repeat this) in sublimetext repo?
I prefer your from and to order, and also being able to use a tab as an option seems like a good idea

**Comment by themilkman** [comment]
Hi @soandrew, thanks for your response! 

I think it would make things easier if the context menu entry would be changed... but to be honest, I do not have a good idea for it currently.
In case that there is no issue in the official ST tracker for diff direction and tab vs. panel I think this plugin really fills a gap.

So.. personally, *I* would not try to set a maximum build number for this as it still is good and working :-) 

As a side note: Sorry for making noise at this topic, I just thought it would come up anyways and confuse users.
