### ISSUE TITLE
Command instead of tab context menu

### ISSUE THREAD

**Issue by rudiedirkx** [soandrew/DiffTabs#9]
I like using my keyboard more than my mouse, so I'd like to diff 2 tabs from the command pallete. EasyDiff did that 👍 but that one doesn't work anymore. But it was so easy :) EasyDiff diffed the last 2 focused tabs, so the one you're on now, and one you were on before. I don't know how hard that is.

Or can I access the tab contextmenu from the command palette or keyboard..?

**Comment by soandrew** [comment]
@rudiedirkx
Supporting keyboard would be a great feature! Thank you for the suggestion.

The last 2 focused tabs would indeed be hard, and to me it seems potentially confusing for users to have to remember what they previously focused on in order to understand this keyboard command.

Instead, what about a keyboard command which allows you to choose the tab you want to diff with the one you're on now? So it'd be similar to clicking a tab with the mouse, but instead you choose a tab with your keyboard?

**Comment by rudiedirkx** [comment]
You can choose a tab with keyboard? In a panel or something? That only works if the panels have a good name. I diff mostly unsaved files, so ST makes up a name. That's usually good enough.

A keyboard command means accessible from the command palette, right? Not `ctrl+l, ctrl+alt+o` or whatever? The command palette is great, every command should be in the command palette.

**Comment by soandrew** [comment]
@rudiedirkx 
Hey, I just pushed an update. README contains the details for the newly available command palette command. Upgrade to 2.1.0, give it a try, and let me know what you think.

**Comment by rudiedirkx** [comment]
Oh yeah, that works well, IF your tabs have good names. And the current tab isn't in the list 👍 Very nice. Thanks.
